language: php
notifications:
  webhooks:
    urls:
      - secure: "D0HOjqQJauWHmOvKJMHz0SVw+AW04kVDGWMSSPmhm52i4rKcS/1iFbUmpO3LZUtfu6Wwmg+/gL2Za+QqMLIEyoWGlY/bMW5Vdw+7ba1COBZEMCZ2diIerOCJ88ZTTxMcd6B40vWJ8OcsxG066PKEbzP8v1IyAvyH7N0QwgaAr9pPEkK34mKoiJ12Uq/AJ7Rqon1NXRw65W1O6/J1iP/kTq727EFZoZF+E/PfMhboGdWrQruKrJUG/5LHYWoqJW4R3RAMgQFKvfrxGYCyagxM1z14p1atQTIHaZ0eRJqYOTDXQWqzT+ny6vodxekkGVqH/pEUE93sGs0gqr0a8CQTgkzJrzSIXbN2ClhDnzQ5hqpM84nLI0Om2YFar0++9i5M6WWz/39Li6Lx2G0MyUOtXEvqrK8f6RYMah4sZcvzENtlMqEcERwryD0mDxf3ET4r1lG/x0L/lHWJl7gg/JJ5PtIlUxaG65dWgJWf55t2LcBryfhdS8w8ybLUC0OCA9ujY0iZFEIUYyBwolzESOvl9uqUSgn9fqH69msRi9EVhtjUI2dJMuYj7FZ5Rqx4iAzqLQ68nknLZ/Rqjjmp4b6htt2krVIS+HeheRcCO94rAzNwWL3yync4gifvzAjKSuebPIUHTR0R+v8WC31JAGjJwqNuqrYH01usW+fkqkKKJ8U="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always


