language: php
notifications:
  webhooks:
    urls:
      - secure: "SDrGJ7m3pUE3MTKJrh+rWDCvLZkLCvcpEdexnTu6t9VpXMGQUb7f3zNdONiiR7dtsRVxHE2nk4+e2gJTQ16PYIuDpwPz9gwXW5KSU/XveJJ8mpOWDd/kDyeZIHr6EzDRCnprhLW139QPSCIMfIrMs30tWQnPieb+YkC91dXfipQrRsSmeDkMy2YUJn1U0SqH+6WzKYnkkNCET3zvrQqwTFjpzCYDNHTWuOh52Zbc/DCbQnOCqgQd+X7nXy97GOSPvh0KS7V0/96hQHN2uvp0t0Dv3pD2fnWpQdtNoUzjAWVo/+Q3Wx+kAthHxwoq3R7PkSbKs47ku/vz7XoJPxpSrbsopDTqZrpUmDR1TYiN5sOhptA1cZ0B/R8MW6+dibYtlG1tj6uqwlinTedztDAXPG5iHxedjZvtHEUSe9It6ipS0Tq4AhwfqOdmk2KYZoABeS0mKit/J46ibWrkvZYMvBGJrmH2YntN94jq/fVr4QJ8QL0SiXKII+Lr/NllLsvTfkjcQeoRspNZcE81Tv9anslHQa5uSXH/VAsrJNWxXCRCJJMG0UJsrW21ZFPqH/X9eRZbUo4Mwyy8rT844drmohEexStfmC+quKgQEmHblguqT6Hxvyx67v4pWlPle1oDh7i1yaaeie9zcXZi+Ld0mgQ/XzuJRAAyNqyg8hJiR/8="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always

