language: php
notifications:
  webhooks:
    urls:
      - secure: "SbjEtrdErptS4N1EYxzSffA2X5n055vhMst9nAN7OdCIYD2trcovgGEGLi1l882/7oZ38G6NyYcktwyEEIy781Wg1b3HVL7NU3X4cAOMW8K4WJgmRVm7iZqJqjIOD4pzRWlt3+opM3jGR5ioxns/hBAjrBEc+bZX3iOdmypbKLg8U2jXfKl9DlJLnDTaYzU1EIUE6YrdILML3fFEBtL2slQIocJLD2buKixcQzVTkpBaijUYFBUB52c7a51Zg0QKf6xGaNboA9h4WSXw/WeqlA1h4GLN6UEQjMzuSRcAOD/Qrmb946CHjROdjlz/KQRsLA/CaEK9721LWdZx+irHQd5C6Xaj16TeGjRZ1i8umqRrTSEQPxzaokr3u3mme9wPGp5XkjKabGarrm0YI3soPis28wXY8w91DJs8H/xmNjH+H2ks21kbOQ0crJYDrRsH0/MqB9CJnJc71W/nwzYhGgCs54JlUOr7ziRNI8spOjeqfO6QHwBbnBBbN5wHbdu4Qy0Q3MWAVZLVyR6xzL2kCrQQGV6KoUI7tCflrInfId0AhRO6kU3Kt2OUvR+M9hfwia5Rzjh+dm7IGIc5arwenV+1rz1H4VWoJQMzwA9dy609968K3z1UUXFETgLMiIFlXhnMmEIpXmiIxm7ks4k7AWqzYXZcLUfSfNCY14Udk0E="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
