language: php
notifications:
  webhooks:
    urls:
      - secure: "Z6+3y62NMgu8y1/WPm6XXKmDH+Q/E63h/EYUrcZdQ1uHzPwPCAcZNBJztm456xGu2P7H3HCaBcwKqVj+evGPhGEXXEI+1aEcZEJygiIhP9tHMld8ChsqsH3rF0kT9el+KvsuCAndyzgnkbGLQXxbLWdLKre+6lQkbf4D7mq5z0PAiVpK4xE/5UstbK8VtKr3a5mxMOCVE2+OOELeylQjZ1ZYBnebjFk8lAIJWP/OQ95zY7IOe3e5swhJOpIyxYp5hm7UT6Tg1bLAXhFJvWEF20FqGjf5HiNx0CY4h5Jy0cpvQ+lM8WumAzZLpxISP3Mj+UYNcO5vypTgvN9Ecg7BHyil+vZHDUv19Inup7RqrsM6g4dLA8FUnEKX3gqBwAE/AhM8FDP1bQplZtIbzgtlUBcblpvq46UVHgVWuJ+5alRugHrf+bjYG/ot2s4+GNuQbH5U/b5Yu2OeCtA+xM53AGi5+mcVqnS0XiQuHq9yGcoGryAJQs9juB0ybAqQY6zu8J8G1+jT/uIgbcGjeRNSQJeSnHWJdkukBCTb0k5otLxAgbZosTCHm1SiRGM9mu48YGXi62DQtdCyblofTshT2BHEwZP+Yh7yVLo9Z8AR+IjLu+5uDogWsUwuACy79TrKmWIAsVpmzbTFN0+K0NJ2mC5FQr47RkBOZglDpJgm8SA="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always

