language: php
notifications:
  webhooks:
    urls:
      - secure: "pSYon9hmcSFyP70UN+f8mwM0yqSlv/GGzRSZ7lKyqjp7TqJXDU5h+zq0kDWCrAHn8oRIQFGKRfQ7XPLmMXuCftTKW2cEDiLHBkMwpJ822CHQX5V5TJSPOhAd9rtvSVAbxh8u8phlFVnqylSoMoaBpXbQDKBp3KBa/R61XJaaLNxhCdc8DUXrTbf62VVeI16st2wAX+XDtNXxLaznrI6ExthXODrQ+uz3Ojui2Z2hwsU706vXitb1iuF/EYm5lMKpuNCvODuHtLMCYk1HeG1Kf/ptjOIzt3+LA+RuXssZVTg/k8nJpKmI8YCJPIz3h8HeIE710bCQVG7UXXBkHljkvabYqVuv0Q6PWZn4oFDPJuax4jcrBRZCbEo+84z67fWZXKe42PHIrVC0t9oFioFJI7GUABwuo+H2fix3K8wpxpPFLmM1XlRa+u5FzbGV0srMLgua9BxzIW3TxcYQ5y3HI6qGzNzEMnZFEHjKlVc6iNJwCHInCkLEvNjWBgALYuHytAp7elycFmL15HlkfcFIi5QNRLPLQg08UikY/a64My6phepzhvIkCzfjJkM2ntwUSEQsaK35czgAYoYsHyqkLTCSwf46w0aoDK24nIKlSfQWbFLHgqbjB8GzBG/nVmMwliyfjdkQmVGnCnuWUd4kGTvp9OW7CAu220fJSC5cQVo="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
