language: php
notifications:
  webhooks:
    urls:
      - secure: "ZSESJffUMCmJtVs2Wn9eI6VaF46RPR23ldPSPC13UJ4ZJUzAqj6fgub+0xJNQtewcdtHQG0AkxNv2shuj2r9s4U2Il0R9k5LauChtOdmCYsFzDl/9esEnDeEFqkx+VhHaEGlmkbZxqYOHU15/lCiLpkzcijMNyS6DaZ6j4DyiB7CM/F9Jwmo+t7Olp73TZ/Kb4MZo1933DhNXEBVsL/Gn3tD5VzgI4ouLlDTmkU+OPhDPKZZGeEcBsI2aOBzChjQALAcPi1ONHmZCQRaf3tjciTszNoSovuipbIkYS9JE4LPwQhDFph2Bcz5mq0mVpIDwGearg/7QK3hsLsthtswMrWTJo0/7KXry+A8FlKoB2OqdzF/ZRMp4G41V6Ie7bKiELz2X/YS0TwTp87y+i9v4vluaHQT3lTiUw4cSFpsiAU40tZ3cW5V5K+wnmSLqgL2TQzQD8r15X30gCbbH5P7uGejt7DcTv0m4dNWK3+JkHuH/0mzroZ1G+GtZAz2JzglaP80rd+Ji2djgl4IFZrvjA2PsCVIh5bONF2Fkb2Ot1MQno+2OVMb7pgyM/P3UC9Z0IclHWpP1uWDQNictTVunEjBs7lcWkNpbbuPNCZKJEAM10yxNlItCGA4gtPhohXPb0Shdy0hcygECs3e5H6AIG9fE0rsnNa54KKK90dAo/U="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always


