language: php
notifications:
  webhooks:
    urls:
      - secure: "CyGqP6AXY4fN2AVaQStIWHnW77QOaecJopgfhGK5I3aLL9hygz/3K370G4SzQIgCzFWik6ZakGP2gvKyt0AYoD5ggwmNhyVhhhZvZ6zQaiiaMW0HbOQF2JxhxuFGQule/FvI8g/yJxYPMx3De5FAjtmCzovrgzA0waq7xyDc1HZCyeSwYpDdsrsEXlmEVTzB21umS6Y+d1JSy8Jqfil9gB84ie3sxtHH1nvcvafkTH6PS/xBxvFvSQdFwuUisR4ABKJmwfYsUv9MDXWwDIdV1xhbIeplpSuSzYFEbwx2Q4BvUSsAbSccsUweMnCytZI72gSi6pql48tt2RXu4XOyoA2uOpA8bXQARhZGxgop/L/4yjXvamp7W2OUO3fq4l+qmk/6j5mSEGAcVnr7OiE+4OFaqICeulJvDods+LCudnUydRS6w76+0r5zMst1bbYHdO89oNM5leONdLsWHEffuM1OInqKAKE47GwYK1JgoviNqkXaQdR9w7s8GrJFOwdFJR8FN3bOGpEf5rjjVXIgh6qjfZCWR+13PPSm1i4979WVKewIlVZ5wR3KxIp/q0fErBoBrAxdhwvKUcwwsHwoZ3XOO4qhWWfpBvZNHqEFEY1DODJepeFWEq63uLasNzBjFrV3ssSzFzsvAgWAlQnMXR0ZAx/jlXWLIAs7w+SCK/k="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always

