language: php
notifications:
  webhooks:
    urls:
      secure: WOK6wPb6L3Aei/5HsUm0AiEztC2CuYpGM6/wU3V22obMQm4mvKd51RV4F+ErW9O/u5rplytdPFmy+Q6oE81qnSbkvP2Nwy2lmbacTXGTizr54HJsFJBTnHIqTJ6ODvFCwavdFXKHnE9NiWTnRETQ5VgoqBpdHSKOwqAITaagWodnnakHvO8oH4j4kbXNHQJpeUbMyqg/eiNerbU5fZ9T5gaKGTA2iKjcjESd/noF+nSYrRdLJY0Hn3emdJ9Q9b6HX1HFxEUohJvJn6chk9tiWaOUuoXp40bPR7UKs/g+WYuEf2DD/MAOB+liciyI+N/om3UdB4b1TA8D5wUnyRWMlqPefC1tnq1uq4rvfE4KwivSS0ImuPqsnYFjbQYuVmi2ax4GLcC/RBwoNHI81pOyESEMxNuFVfLhHOQDXGsbfaT5CsgLmQkZMzZ9HO69pFooprKA+ngaputdKUlA+wCfN9EDfoe9MYMS7w/VStonNOuoKymE7LWNIvr/t3Hxs1NtscJS1+2w/jMNTWmLHDVnilDnyglxXpA5W85/ZZwJBXZu2fcZ6pemUf1t7WiYvqy+x27eYleT627ohS4sWer5RIH5WUTJvDEz+GaGLABg+Ph+KHgyD4qJXbnwTR2FPj1++MYhsF4Lb+DRLSfrZcQO6JWHyWorggBU9vQ79EyqLAE=
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
    
    
