language: php
notifications:
  webhooks:
    urls:
      - secure: "DUUtc8vZYTLxHRh1vVNoZqz/1XJZvKsn4Auh3lidUb6ccXv3qqKzxTZYMlNte8WZQV3FdrHyit9no0xTCCy0nte6+3dwsl0NM1JbwieEB6phNOIW8evqSVuPtJJY1sDXKrL5raqp5SucMgbdEgxaSN0ThkscY//kjhaR/whWFhQUKZ3skzhmb6lm42SrTIKmcqXoz3h+f+GZsq4h+xfHlTJTroPmnt4P0kdVT+jy43WpqkQkdCXzA48c7b7xYAtNuqSVQJ1gKcBs+iJA1XJCfoYf7GuyRGG1btPrBgLGa6tux6VcBv80XoMDXUwZXacMLLL7T6JPutzmI1BvtxoZIHIbZkHWuxEhMvvCPMhwyrflO66lysmUucFJ5MPNTFoSYzxppwndfxMnxD/5WWbMYXMzmFaqqPUoXWxqVDiXIlYSBmmqpOlZ/p5ryUqz9VWxiqfwJZ12v79Tn9KBrqtXWEIOLVKuPX6VRUBX4X9D2t5GXASU5PklOEQmvNt7xU9E9vLfSnw154qUoqObqyPfaTHkAOtGnmOumvFWAQQ1XFU7osXs+QZPHY/41XhL6+D7OOaTqVWVb8kPlObJji9qNd1jKYgk2ErW1cIbr2vW0UXkvt+1H+Ic+H2piasviT7VrHRdGsnNT16VMRKsq4jFm9iqucE45reot2VN3xWbuwg="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always


