language: php
notifications:
  webhooks:
    urls:
      - secure: "ehbB16FqUGS/JecvAhdZ0KcjszdWeJl1CL6J/utPxDHUUGER1jJ+uM/kdmiyksxMNMuJb4CjHnC4shZt9zCuQsyNwqblTOIiizkmPVFEebglMciCOBsgMH8oPfCYRoXtT/dW2JjHFrY8qXwekjrH1VaVwYdb1Jf94LiFx1dNu/98koioANMRnnvysIcuvF6p31wKCwio4ExndEvZQo7LM167ixk0Pu00+SSV9E2aAPBrZpsjKxNQThI/Yv9VKiA1xPePQJSpmu0pjT5C8AW5C/d4EGB3OLKqZwO/r9eQZN9lmLJYrDGZjhK3WTF7ddyONYEWt6uwbl8NQxEyCW/RqmzNLfGIaUyLpGZVkjlnH4I4XiY+Gmq8Og1aVISglULWWj7mKUth+oIdKiE36TzrvuPUzS92/wEpWOKPHpMYtYs5TZA0Yzea5FrKd2pbJlyiSgf3KElkyIAbZVCFegJSWeWbgOpZpp6ywTr7E6NTJWF29ThybUDAam+p8wqljZm8nUQ2aXCLyApYEASJEzCrlBGEfUCFZAH5o2/9hGrW0bYQ7E7UYr7ulNJBh4sCVJqfYoRUzgDvu64g0xEAmpRnvEQG1tqFVMm+AgdjbrkZZGw6JEC+jcItUOGQBcs4El34REkvjo744zdygDILGGR+suLf6lc1KrDlsqPIH3CJiM0="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always

