language: php
notifications:
  webhooks:
    urls:
      - secure: "oFStTIVZCRGONGValfxT2sWTUW+jQTCXhNbjbC2tJshgzOV85sKcELT5j2CP/6H8O+eJjVr1zoexuR1z9oia8e0q5YFsVzPa1LTHVIQmX5ykzz07sbwO88VaLC1AvW0eOazkfZy88KOU3BCLVxWq/d5xeJI1PP6ZbwOHmSiHXrpan87CHTUFAYwq8rvL2Qdwm95J8WkcB6JpdsSL4EwrJUOFinRGsrSL8j7PjL5E502aHCKt1jtJD2kFZNBA0Wnolhr1cJUjDQKUuKeknrwGOzXSNQ+6xA2aHoC0dKAOOZY+43saH7XPxKnNL1+9O6MnbXvnLBkgFMsMtsK5WXq3J9PSSm61A7m2zJ3BL0i7k3yKs9yZuC16f/4nK0hlxfqUMY3sSEPX9OCJGRe4A2gLBJPrIXxjpHHdYI6GO4voOYRy93Fo3xr/K/9QzADaLFETCzndoQ6VUr4xH4w3FBE+zlKETC4hGbO0H2BZb035RIvErqiza16PGQKQsS6D9b7qcfTl/VABt4IH5XB3htzpBIsWqiROl4o46dJGBiAziGBqMlDNV7Sr4ekUP90xY7gFTVZzTZUGtOyKvhbzIy8YIQKLJUw01C5K3mCYoXLtTZ78NNa3FNCTe1gkD7lrdUIU9O3LAbAhjVKChmGGxIdsaXbHy5glbM28/dYgofNRIZU="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always

