language: php
notifications:
  webhooks:
    urls:
      secure: OCyq3zLL2GGT3WcY5GCXtW7+2Ph/jbr10rI7wMGsNlyRwEp4B/F6KuUou1AhAfNmrEvJZsKK59pw9fQvTJFpOEaGX3Vs566uVCqr+0ISZpf0bvsNUnT3FkAmdy11bBlKfQ+0oWeeiW6nmUzlkdv30ex/EDUfbMNKCxrtzOX3mCuom6Q9bemG7Ojfwq259mZ/zGMhnWo0E3D7bzg2P5OjRLMsFFMR5DTjH7vGBtGF3yUcXKIoqWhOMDv+Ql2vWGymicJEtIgeOMFiiBZiY0DG91oVTleoJ8K4BbiPjzgBVWyfwcHrXuAb6Dpa4j6D3vtLznWIht2Yy+2WJrhM3OorlXNHeUBSvEyrNtKP8v3fLSdVAb0iBxn9nu4oGFy+mgk9hpTc0q+kuYviSraPvbs0gzi80DygTPZg2imz8xWQwig/8pERVEhGO73w/tqm8KqVnhVAfU0Qz61cJ1GrqzBt9hcHcoGaehoUXUkNEV85XFRLV6sXKS7t4Y3BAwuPGfpeZd2oZ0wlBBsxVZeVy8Uo9durfexbxef031367fhoyS+nKnw0zf1uPXRbtxL3gvpNuG2Be+VzfugqkGGQ3wYJykagaJJdztK5M09A+VljYDFKRuArLE9CKG/eVuklN86BCxBoSSFEAe0IEHA53ZiWC7dNO2Ahz8Qx3ExM4/u4cWc=
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
