language: php
notifications:
  webhooks:
    urls:
      - secure: "JpORZuk3fQoZJGIPBrl94a2ngPoNjVYJdwi/5ZqYP6O+IlStu+SkIieds2nEWcWDchyF2gMjP53c8nIhC8eBU2ZnhE+eK5fddbPJoII0wrBJuo5g6zMpeN7r3UFYc9ORkb6oha8wGDIi0m73AjFhD8a3kDPxIIAiD4E3L5w17b8zzoZLAlxVfZaZbDLgHBU5mjMcNGpwjfZr5ikkchITWw399xzGEuc68pVcGwXYsW+Uj+DW8mtkSnLeIr0PCzkypfvz/sIa4DVxpSKslCGDRDVFKV0APtkKPxOy3uq71FrYjHGAnFpOQkKjev+EAkAsAHsmNOBtk3qYewWgdZUnPpIPbReLRvirXysygqDVl4ytDb+OakQWYFo9QFrzjfXKccySBtcHnxd4XTXihzqPfRDEJL42RmbufPNW5gZTegX0pkgGJDy+nuTRUZ5RqNaOvZNl+VSWeEJQja2ZochEFdkgQje9GFoAOGFSrOsg1VtRC/5kTki+SMxLQO7cLMv/H/0ZpxfAQN1OFOBA84B32KZV8KO44pATbJnjgkXdzhrNzxb1Ov/M87aXQMSrv0mGxDA3BDSwE+idpxmsF19lXSsFJ7ALHvXAJ2FlYGV+6VAWZPOkGeCdeoTl7P1U/n8EdB2DDUfPQKGbhD4RFaYYMeL4vauyYFJhdvxiifZHu70="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always




