language: php
notifications:
  webhooks:
    urls:
      - secure: "aoGgAulVQ3LZyB7WJufPgD2suu7ZystfuwoXzARZUHJ/Z3WeXGgFEUK0k6t76zzyNP8dxjiIb9lJUFb+/ob2SOhO1flQrgF54szvr2Yor1kWWeGxaRE4cvUy5j9H7xKFkIRWxk5hmOAZGJAVg9jUr/ayBXcu8NSNseWUtGn3N6n9f3dSyCvGq1C3/Yxqtt8e4EvYaRanUGwD+Suyc5+nEMxuIl2y2miVHeHptz+najDwOzScsk16TLTIgCPaHUnIKqSx4RLOAn/oc+/sL/rRDKFZn9Wc+6R0Xk8UIj1kWGXFvCBwmM6fsbWJIzz2SNwxdnYPad/kWOLyCZ1P5s6hbmmbI0adSSWs9kavrVozT4YUpHuv/ZujCjOmwyhp5qD7vVFwtxzREkQ8ih/adnxvVYuVksxkt62PCyDh1u6Tg2end4OTVIK2WsBxbr2Jf3/mCtQyICnzs0LoH/RuFOPcgnTA3MiNEFO7ibOwLZXMmH4vZIHEcu+bjNGm+QryWFoRmX4nXc4r8PjUSNAmkC36TEZoRM2f3h0Eg1Vs1tky0NpqMPbaoZaqDcjj0AjT/qiF9xpTgDYzO9Y7eb2ev28PH/g+xme/DE+cc95lziryUOfGtUZA/TZBPly7BxUbZZ81/rZW6sDRtXTI7sAsKt3ueYwckoy1aJoUy4rknHw4Eeo="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always

