language: php
notifications:
  webhooks:
    urls:
      - secure: "IgiSwntXmHJ7UgKj1huB7y4NMwcQFxlA5pHEp0JgtaUj5DKM9M8m6qqjW71UBLEjCeN4k5PBzCTrhqr2aAXsNP4miTDWEMGAMeqGtoUrRsSZsQxf1GInqU+vpRZsmjEgCEpXI3Yp29OQoHGqTqo86Xt34ASGdQnx3fkZQL0H5LCNRW7QHS092uPPkuFRjmMONoFteCnWMioHi4p/yE4usucpF8gu3ntbTrSIfARPX8a1fVgFCRkDODaRtupzHQyqZvFXFln3Bi4BEdpzMl5T5nkaTD2DW0nuYZk9LFtRm3AlJxOVcjRaD7O8uVUqS8ZGz7h+cID2W5nJQ3SHMA9evjgodVupqqZWcBCQ6DznvdDB0XxbaFo2op8J/u7/94bzDZl15WjWe3WE3yVJw2Rm37Xq0p+2bH2UQCfRzWfeNYlRsLmZuJYZuHXqyaNAUIm8Vv+I+Jx1RgGB5Z9jO7DFcx7IxJeFira1UZmexboCxK0SSdVZd1ORPvuCPUw2v+Sdcg21YAmCIYWZlgNynvoE6i1wLPT/9xgV0hzXGxiu9Dn+7BYZuZtFu45enV4xokr2tzF3UXL9r6oDK9yFgZFYlu1SHUMB53pzAhpM4QUQFB0qQ9K3f1oh9zVFHIIEPqiLJPvs12IVzdsNHUXj0NOJw3jd7REUoOF/SLtQZqe/p2E="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always





