language: php
notifications:
  webhooks:
    urls:
      - secure: "IfIcbHl5p2riClruQy8zKmLcPw+0ssuJxObQCTa7YZfAsKg0vwXMsA/qJi1XzLA09KQYwkpP90z8MT2rHU9EnfdGUkVRDaeudx5uYCwH5B7ugwWzk6JKGUCo7Nwo+q9CMek1wMJXIYoCI05etwJrcwx3Au3PeYxyOwgZuPO4kCHTavbUityBDZtyZXrWEcOHqP76/5HO7JSytekaoftiZLZv0GXubcqgBaN27aDjjrPO/AJgM2ECpmbkFkc9HXHhtJWx+3aO0ASj00wfVtXyojgycKlrYIkAYsucPO5V1JZiVNW/Riui8bPMe2paQzH56O7oBYTr/2XoFUxt6T4z6jVzbp33erOBBhHNCTqPNZWHRb5PwGBDldpzSq5PalIPVElxnFWzSUvXeoVezM74Hn+XNihhM81XkHzxIJf73D3ha+ZYBBS1bZ18RnxEmRNFApoRpiJWnfw2NhwPL3/p3B9PO3GVsv/otV78SxPLPCMKQqv74AO6nzfgNRmo4FNEAnXaTh2RRcyM8qAiRa23I8mZXAg7hF8U+BGe8WKSh8b8+MydXeCqQTB7c2vOpGAkKuhpEHf3w7dPZuypl3Z/QDdvOoKp0vlyWUKMW+Zakc8E6MznoaQHyO8LeumzbrZJFfGoxJ1Fs+Y2yHSWdEv/jk0tmJs/YPcQkuY7sTOzCi4="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always

