language: php
notifications:
  webhooks:
    urls:
      secure: DLxjAJPtVEPIM0ohSxBKrUKdHUYu0ebyzR4SvkHfKVtE94t8hKI83CE29ndPY//3BuCDLt3m2MEIi7Adf4KYCyz92XKqcgy+nWjty+0rgxPTjf3qd8ja5NeXP3wp+NBQ1OHOW5gk0NpuipYOPBHD4NeNNiyvPuB1bWBi5C1ZXj8BZK9T5d2NIH6D6mQxVvGpfSGOxoE8GUCMEzzX+OIUdQHXdsC5Dr1Y4HnxHobnfiFG9tIoR6CWZ9tizUz/I3KDsLpWLX/G/l4hj7HZ1IzvrjXNnMykhAp4Kvo+b9cH3m0ZQM1/a0Z3UFNnQC9hHXFTLi3r87q/3GIPCZu9hKjq3qPm6I5LgZBdWOiBt/AqTnRH49hVHZh25y2FsJIn3TwboCebo3Bxi7SWYZvEQZAYE9d2p20YZ5wU+j07oCHMdWt3sgSMYkHNLwMqoIlVVCmlp7ZaAGIT/jZ8Dvx3YPsCBW2tVwet1bcDffonLr23OoYs5lWhGHICwYuokeqYjw45YieTqT8Hl8QQvTBbaJkQe85nOMc4F/oTQdyep4U3xnA2f2lKbQM01rINCKpmktpnJtnXdULBu3O+dVQBTo4Yl3fw+kPS/M63RazDygrzwhF/qwUNiWwtuOML+TzXBTsNkoQ6qglKcezL/2XYy/3EynoZr7g1HiOscNmhRNguvgg=
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
