language: php
notifications:
  webhooks:
    urls:
      - secure: "nhiyH49HvgKdwPIoOKEZIFjHBmDNV0t33krHSp/ypBKGbM0Fqqi8bVFpYr9mTkX7KpCbJ5hZeASgHK4GD24FqpuR/M6ETSSF3Jc7UKqSPQRX/q+T9PyogbgtKO1Wn6/2VQR/kGO/X8bytNh2ocC1+zL2zu36Hfgm8IIqw6ussP15VltljfvubkceNXC2qb9r6ng1o6+/J7YfcnNS9WRCcE5xBK+mhVRPdM+GsbG937iS045DbBHmrbgZjbGabXCXn9FVV+6mj5uA+YSt6Ra6trnqxMYIV8A608zcdI3XJiAySsVCECk1jcQ/x50ynNVuEK2Go3AdSn5qNTZO/YKNfOYIeXV+2KBz3wW0/Q7qQDbPgnL5BkXioyVFgUtYin4gM+1dpned0o77vxF2qlgO44AtbdGaWt8S5AQt8ds6glymRKFb3cQfrFUqfl0LQ/57OBIV5dGbedfAiC5y/m+57YwHE69paLo1JDLwSvdcbpnnTOJOWIb/C2HLSRUegztuMqSmZLbX+T0fMMmHNmrc32aJg8GPfU5pxuGjfPMzrmAWXsqbKKMgAku+4gSeC3Pb2BsoDO1kGDSEtTiI7k1nXJzHR3VKdwW+RLvGA+6obNnM+RUXd5F8c91vifOHiaw1w+WFcW/w96qlnM26sxjGL7/DZDHCxQXTjYEKW+N2o5g="
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always



