language: php
notifications:
  webhooks:
    urls:
      secure: DDvUailXI4jM2fXftjg8YbErhD7/fQHqdciDUG6rhNAaD81hpWchvXdm0w0fnI6q4Satqdno9YK60owZtGVd/bZzvgquFM+X9G+/hfnQqUptp/zwaW770v0qA4OXmbjQ0OCAr9jsC0DgBsEnu75Gmhz9rtMqkkYoZD9hNcows4sCZ53e+yi5zYp8MVlUnZzSG3uWqNT/+54eG3/U7FfSWNt5AHnuHG0hLm3LLfBYuVX+AcXyqudU8zJKK4xkAVj6F0b7XaTcuSthNwm3sujYl/MCVIsuTJPEtMcpkJx9TI5OPbZMEQZgrLj3Fh91d9zv5AcBPmcweTRuEp4g6R8lElWhQcpkcNbII+3m5jalq5czF5/x8KJRb4rAZkH0Q8pYU26oyIf72Py7dAGkcr5iaDLAiwI3Z+T9zu9cFW/FOcuhX7+ZrmY4et7SIPokivxYFBU3ZJnon2Ty4D40eKAiT2QCwkm88K6QwR0cOUrcJgGYW1trjboEFqndQBxM+NPszOa8k0Jk2o7ZGUPsEhzUc6c0+KfsGzR2GDE7ZatBflA8NePo+s8W0O343CKNCTod/Zp7mIx3pHoLedSR4NHNYDajHgFku1+hZe3Jhv1PRy7B6MBiygm0E3Ar5sk2o/HlaWRa0nfQWoMREw4M26v5OfAyPE4wNnRgh/TZaLTpQJ4=
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
